# Generated by Django 4.1.5 on 2024-05-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
