# Generated by Django 4.1.5 on 2024-05-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dental_app', '0003_user_reg_dob'),
        ('userapp', '0002_appointment_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(max_length=50, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dental_app.doctor_reg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dental_app.user_reg')),
            ],
        ),
    ]
