# Generated by Django 4.1.5 on 2024-05-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_period',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='today',
            field=models.DateField(auto_now=True),
        ),
    ]
