# Generated by Django 4.1.5 on 2024-05-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_appointment_time_period_appointment_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
