# Generated by Django 4.1.5 on 2024-05-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dental_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_reg',
            name='address',
        ),
        migrations.AddField(
            model_name='doctor_reg',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
