# Generated by Django 4.1.5 on 2024-05-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, null=True)),
                ('details', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
